### ISSUE TITLE
main.py

### ISSUE THREAD

**Issue by dancayairdrop** [ccyanxyz/uniswap-arbitrage-analysis#1]
Hello, I run main.py and get the error, can you tell me the cause.
gas estimate err: {'code': -32000, 'message': 'gas required exceeds allowance (1500000) or always failing transaction'}

**Comment by ccyanxyz** [comment]
It's normal behavior, means the transaction would fail (the arbitrage wouldn't success).
The code logic is:
1. Pull the state of all trading pairs
2. Use depth first search(DFS) to search for a profitable path
3. If there is a profitable path, estimate the tx cost
4. Estimate tx cost failed, means this opportunity has passed, if not, and the profit can cover the gas fee, then we send the tx
Uniswap arbitrage is a competitive area, you would need faster ways to sync the pair state to your local memory and faster ways to search for a profitable path.

**Comment by lxxysa0601** [comment]
> 你好，我运行 main.py 时出现错误，你能告诉我原因吗？ gas 估计错误：{'code': -32000, 'message': 'gas 所需超出限额（1500000）或始终失败的东西'}

你好，方便解答下么，还没运行到这一步，前面有个问题请教Could not find artifacts for Flashloan from any sources
