### ISSUE TITLE
关于计算套利数量的问题

### ISSUE THREAD

**Issue by nanlong** [ccyanxyz/uniswap-arbitrage-analysis#10]
在计算 A - B - C - D .. - A 的过程当中，每一阶段都会计算新的Ea 和 Eb，那么在过程中出现 Ea > Eb的情况，是不是就说明后续也无需演算，可以确定无利润了呢？

感谢作者，从中受益良多 🙏

**Comment by ccyanxyz** [comment]
应该不一定，后续叠加过程可能会再次Ea < Eb
