### ISSUE TITLE
Gas estimate error

### ISSUE THREAD

**Issue by bitcoin4cashqc** [ccyanxyz/uniswap-arbitrage-analysis#3]
not sure about but, is "gas estimate err: {'code': -32000, 'message': 'execution reverted'}" because it's not profitable considering the gas fee?

**Comment by ccyanxyz** [comment]
It's because the arbitrage tx would fail, see:
https://github.com/ccyanxyz/uniswap-arbitrage-analysis/issues/1#issuecomment-705647636
